### ISSUE TITLE
Add 'save active pack' file menu option

### ISSUE THREAD

**Issue by Aractain** [donkeyProgramming/TheAssetEditor#123]
It would be great if a 'save active pack' option was added to the file menu as when buried in lists of files above and below, trying to find the pack name is a pain and sometimes its not even in the list because of the search filter. Its a small thing but I have had it crash when clearing the search filter to see the active pack. Adding a hotkey as well would be even better.

**Comment by donkeyProgramming** [comment]
Good idea!

**Comment by donkeyProgramming** [comment]
Should be fixed in latest release (0.58). If the bug persist, please reopen
