### ISSUE TITLE
Cannot save a model with new textures

### ISSUE THREAD

**Issue by ZioCru** [donkeyProgramming/TheAssetEditor#140]
With Asset Editor v0.46 whenever i try to save a model with a new textures (example in the photo: base_colour) i get saving failed! window. I tried to save the model with original textures and everything is good, save with 0 problem both rigid and wsmodel.
![error](https://github.com/donkeyProgramming/TheAssetEditor/assets/130470251/9deec21d-c12e-4ebd-94a3-183504ae5ef3)
![error2](https://github.com/donkeyProgramming/TheAssetEditor/assets/130470251/553341d1-97a7-4a64-a5b4-dd942a1cb72f)

**Comment by phedrohenriique** [comment]
I have some problems saving texture as well, the gamefiles are working as expectedly, but suddenly a simple mode that i created started not showing the metal textures. I will upload an image of warhammer III comparison.

At the game, the textures are getting weirdly rendered.

If the team need support for the fix, i will gladly help.

![texture_bug](https://github.com/donkeyProgramming/TheAssetEditor/assets/87654745/73ae16ec-a89a-406a-888c-d8c4f585e548)
![mod_bug_asseteditor](https://github.com/donkeyProgramming/TheAssetEditor/assets/87654745/8d7c6351-cb4d-4320-be74-2ff18fe98f81)
![mod_bug](https://github.com/donkeyProgramming/TheAssetEditor/assets/87654745/fd543df3-4008-47bb-b9b0-28b4f4b0f779)

**Comment by phedrohenriique** [comment]
@ZioCru  are you using RPFM ? 

I get the difference at showing the textures when I am packing the mod there. The AssedEditor seems to be showing fine, but it can be a problem related to RPFM as well...

**Comment by donkeyProgramming** [comment]
Fixed for v0.48
