### ISSUE TITLE
TWW2 No Longer Uses Manifest Files

### ISSUE THREAD

**Issue by Autumnchain** [donkeyProgramming/TheAssetEditor#155]
This means that Asset Editor cannot load TWW2 packfiles unless a workaround is done with a TWW3 path that goes to the TWW2 data folder.

**Comment by Autumnchain** [comment]
![Screenshot 2024-07-14 211235](https://github.com/user-attachments/assets/ef831e76-e1aa-4140-858d-1737b1af8819)
Decided to add a screenshot.

**Comment by donkeyProgramming** [comment]
The error is not great, but the pack files loads fine. Improved the error
