### ISSUE TITLE
LOD reduction should be optional.

### ISSUE THREAD

**Issue by Steph7401** [donkeyProgramming/TheAssetEditor#156]
n the LOD strategy, with have default, or LOD0. A third option is needed.
LOD generation isn't good at the moment, CA existing LOD may be better.

So I could simply edit LO0, 1 2 and 3, to remove some parts, in every LOD, and keep other parts as they are, and ave.

Excet it's not possible, because I only have two choices: keep LOD0 everywhere, or autogenerate it. There's no option do nothing.

Beside, after some comparison, LOD reduction was better in 0.45. I'm afraid 0.47 is unusable for me at the moment, as everytime I save it  mess the LOD, except if I chose to keep LOD0 everytime.  Version 0.45 can mess the LOD if I'm not careful, but I can still keep it as it is. 0.47 will mess the LOD, there is no way to keep existing LOD1, 2 or 3 or edit them manually.

**Comment by donkeyProgramming** [comment]
Fixed for v0.48
