### ISSUE TITLE
Cannot change Vertex Type in some of the mesh in version 0.47

### ISSUE THREAD

**Issue by Armorchin** [donkeyProgramming/TheAssetEditor#165]
My only solution I had is to use version 0.45 to change it then continue to work using 0.47 (I love darkmode too much)

Every mesh that included/use any of the dismember stump (eg. dlc02_stump_neck) won't let me change their Vertex Type even after delete all mesh and replacing them with static type it'll just change back to whatever they were before.

I cannot change any of the model's vertex type to static in the following picture

![bug](https://github.com/user-attachments/assets/092950ea-fc46-4d4f-ad78-9799c3c6ea1f)

No idea if it's a bug or I'm missing something in the new release but thanks!

**Comment by donkeyProgramming** [comment]
Issue has been resolved for 0.48
