### ISSUE TITLE
(QoL)Vertex mode for multiple meshes at the same time.

### ISSUE THREAD

**Issue by thomasskinner93** [donkeyProgramming/TheAssetEditor#167]
More of a request, vertex mode does not work when multiple meshes are selected, thereby increasing the chance of misalignment and requiring us to make the edit, duplicate, then mirror the object. It would be cool(and take less time) if instead I could select two meshes, enter vertex mode, input the fall off, then use the gizmos to do business. Preferably this would respect coordinates(for example, when scaling positively on X, the two objects would move away from each other, instead of move the same direction. If that is too much, same direction is okay as long as both meshes are able to be moved by vertex with falloff). The ropes here are cinematic and are stacked, this is actually 4 meshes, so I had to move the top, move the bottom, then do the other side, making sure I selected the same vertices on all four parts.
![image](https://github.com/user-attachments/assets/a9027c07-7cce-46dd-baa5-62fe5057bf47)
![image](https://github.com/user-attachments/assets/6f057e45-4624-4eb6-9b43-bfa10cdca11d)
![image](https://github.com/user-attachments/assets/c886deb8-4281-41be-a07b-57b34503340d)

**Comment by donkeyProgramming** [comment]
This would be very cool, but it would break the overall design of the application. Unfortunately this will not be implemented
