### ISSUE TITLE
Mesh degradation on save (vertex merging on lod0)

### ISSUE THREAD

**Issue by calmnnormal** [donkeyProgramming/TheAssetEditor#170]
Meshes can become degraded when saved. Vertices appear to be merged for all lods, so that quality of mesh at lod0 resembles lod3 or lower. Once saved rigid is closed and reopened, loss of quality is irreversible. 

From testing:
Loss of quality appears related to positioning of the mesh. The severity of this effect can be reproduced consistently in both version 0.45 nd 0.47
![image](https://github.com/user-attachments/assets/9bd5716b-1d42-4e92-a1dc-697f6c346ba5)

In above image. 21 meshes. 1 original at center position with 20 duplicates, 10 along y axis, 10 along y. Each duplicate is spaced apart by '2'
First I will show the center mesh for reference. this is is not degraded at all. 
![image](https://github.com/user-attachments/assets/7af294df-af73-4abd-90da-9286af8caefb)

Now the topmost mesh:
![image](https://github.com/user-attachments/assets/3bf00eb3-f0ec-4cc6-bd60-287a6696f4e1)

And bottommost:
![image](https://github.com/user-attachments/assets/0f86c593-cf3c-4d3c-bfa2-135d4eb48c45)

As you can see the meshes have had their vertex count reduced.
The distance from center effect is most noticeable when looking at the outermost left and right meshes. This is the
outer left:
![image](https://github.com/user-attachments/assets/e18eda27-2bd9-497a-ad9a-aa508ca8e5fb)

Looking at the asymmetry of the ears, it's clear the ear furthest from center has been more harshly reduced.  The outermost right mesh appears as a mirror-flipped version of the same.

Those are the extremes, but even the inner meshes are degraded somewhat, albeit to a lesser degree. These are the eyes of the center mesh. 
![image](https://github.com/user-attachments/assets/52d24c0a-a3dc-4530-918c-c536eb4f48e0)
Now the eyes of a mesh moved just 2 away from center.
![image](https://github.com/user-attachments/assets/2ce90790-97a3-4227-aef1-c1f21f59db8d)
Notice the roundness of the iris and eyelid has been warped

In conclusion. Based on these tests, all outer meshes show some degree of degradation, the degradation worsening consistently based on distance from center, with only the center mesh showing no signs of any degradation. 

![image](https://github.com/user-attachments/assets/7f96d21c-ffde-4b86-81cc-f711b031e0e7)

It's fair to ask how I noticed this, or why would any one save a model with meshes moved away from the skeleton. Well I often save meshes like this, so I can mix and match body parts to create a row of variants before repositioning each one to the center and saving them individually. 
![image](https://github.com/user-attachments/assets/2d8f861f-29d4-4137-95de-489c6219b429)
I started noticing my models were looking wrong. 

I think this bug is quite important to fix as many users may be unaware they are degrading their work and the damage once done is irreversible. 

Finally I would like to say I continue to use your tools in all my projects, they are indispensable to my creative process, and it's great to see you continue to update, maintain and improve the asset editor. Cheers and thank you again. 

Edit: Also just tested. It is save that does this. Opening and saving multiple times exacerbates the reduction.

**Comment by donkeyProgramming** [comment]
Fixed for next release, thanks to Phazer

**Comment by calmnnormal** [comment]
Amazing thank you!
