### ISSUE TITLE
You can no longer edit the LOD distance

### ISSUE THREAD

**Issue by Mavrik347** [donkeyProgramming/TheAssetEditor#171]
In 0.45 you can see the LOD distance when clicking on "Lod 1" in the hierarchy. You will see it in the "Group Information" as seen below.

![image](https://github.com/user-attachments/assets/512b9e53-580b-4bc2-8cea-cf9429d4d71c)

in 0.47 this information is missing, see below.

![image](https://github.com/user-attachments/assets/e5a29bbd-7508-4dea-9a06-ebeeea067c78)

**Comment by donkeyProgramming** [comment]
This has been moved to the save/SaveAs dialog
