### ISSUE TITLE
failfast exception, 

### ISSUE THREAD

**Issue by Ravocan** [donkeyProgramming/TheAssetEditor#223]
As the title says the application does not seem to work, I have this error that pops at launch. 

For now I’m staying on the 0.45 since with the others I can no longer modify the textures, I would like to know if with this the option ( creat project ) came back to see if I still have a solution to make it work or if I still have to wait for a change.

**Comment by donkeyProgramming** [comment]
Can you show a screenshot of the error or give some more context_

**Comment by Ravocan** [comment]
when I try to run the program simply by clicking on the icon, 

The exact message and the following, 

CLR: Assert failure(PID 2552 [0x000009f8], Thread: 14096 [0x3710]): ! AreShadowStacksEnabled() || UseSpecialUserModeApc()

I would also like to know if the texture editing was available for this version? 
The last time this feature disappeared was there 0.45.

**Comment by donkeyProgramming** [comment]
THis is most likely caused by using an older version of windows, or not having enough updates applied. Update your system and reopen the bug if it still happens.

**Comment by Ravocan** [comment]
That was it, with a version of Windows 11 no worries, but for now I'm still on 0.45 while waiting for a version to be able to edit its model. I don't use the game assets but the one I create in blender so I can't use a version that doesn't allow editing textures.
