### ISSUE TITLE
The given 'Key' font not present in dictionary 

### ISSUE THREAD

**Issue by Rogvir** [donkeyProgramming/TheAssetEditor#225]
{
  "ActivePackFiles": [
    {
      "IsMainEditable": false,
      "IsCa": true,
      "Name": "All Game Packs - Warhammer III",
      "SystemPath": "C:\\Steam\\steamapps\\common\\Total War WARHAMMER III\\data"
    },
    {
      "IsMainEditable": true,
      "IsCa": false,
      "Name": "maneaters_01",
      "SystemPath": "C:\\Steam\\steamapps\\common\\Total War WARHAMMER III\\data\\maneaters_01.pack"
    }
  ],
  "CurrentGame": 11,
  "Settings": {
    "RecentPackFilePaths": [
      "C:\\Steam\\steamapps\\common\\Total War WARHAMMER III\\data\\dwarf_repeaters.pack",
      "C:\\Steam\\steamapps\\workshop\\content\\1142710\\2794874144\\froeb_armoured_maneaters.pack",
      "C:\\Steam\\steamapps\\workshop\\content\\1142710\\2789978667\\_hv_reskin.pack",
      "C:\\Steam\\steamapps\\workshop\\content\\1142710\\2794880709\\froeb_armoured_tyrants.pack",
      "C:\\Steam\\steamapps\\workshop\\content\\1142710\\2935715942\\@Xtra_Ogre_overh.pack",
      "C:\\Steam\\steamapps\\workshop\\content\\1142710\\3333421609\\ironskin_tribe_tow.pack",
      "C:\\Steam\\steamapps\\workshop\\content\\1142710\\2964101252\\ironskin_tribe.pack",
      "C:\\Steam\\steamapps\\workshop\\content\\1142710\\3261132178\\froeb_chaos_ogres.pack",
      "C:\\Steam\\steamapps\\common\\Total War WARHAMMER III\\data\\maneaters_01.pack"
    ],
    "Theme": 0,
    "RenderEngineBackgroundColour": 0,
    "StartMaximised": true,
    "GameDirectories": [
      {
        "Game": 1,
        "Path": null
      },
      {
        "Game": 13,
        "Path": null
      },
      {
        "Game": 5,
        "Path": null
      },
      {
        "Game": 7,
        "Path": null
      },
      {
        "Game": 12,
        "Path": null
      },
      {
        "Game": 9,
        "Path": null
      },
      {
        "Game": 10,
        "Path": null
      },
      {
        "Game": 11,
        "Path": "C:\\Steam\\steamapps\\common\\Total War WARHAMMER III\\data"
      }
    ],
    "CurrentGame": 11,
    "LoadCaPacksByDefault": true,
    "LoadWemFiles": true,
    "IsFirstTimeStartingApplication": false,
    "IsDeveloperRun": false,
    "WwisePath": "",
    "OnlyLoadLod0ForReferenceMeshes": true
  },
  "NumberOfOpenEditors": 5,
  "NumberOfOpenedEditors": 39,
  "RunTimeInSeconds": 475.6939172,
  "AssetEditorVersion": "0.55",
  "ExceptionInfo": [
    {
      "Message": "The given key \u0027Font\u0027 was not present in the dictionary.",
      "StackTrace": [
        "   at GameWorld.Core.Components.FpsComponent.Draw(GameTime gameTime) in C:\\Users\\ole_k\\source\\repos\\TheAssetEditor\\GameWorld\\View3D\\Components\\FpsComponent.cs:line 38\r",
        "   at GameWorld.Core.WpfWindow.WpfGame.Render(GameTime time) in C:\\Users\\ole_k\\source\\repos\\TheAssetEditor\\GameWorld\\View3D\\WpfWindow\\WpfGame.cs:line 147"
      ]
    }
  ],
  "CurrentEditorName": "KitbasherViewModel",
  "EditorInputFile": "grn_orc_black_axe_2h_03.rigid_model_v2",
  "EditorInputFileFull": "variantmeshes\\wh_variantmodels\\hu2\\grn\\grn_props\\grn_orc_black_axe_2h_03.rigid_model_v2",
  "EditorInputFilePack": "All Game Packs - Warhammer III",
  "LogHistory": [
    "[10:05:52 Information] [1] Shared.Core.Events.EventHub::Register : Registering event SelectionChangedEvent to RenderEngineComponent on IEventHub \r\n",
    "[10:05:52 Information] [1] Shared.Core.Events.EventHub::Register : Registering event GraphicDeviceDisposedEvent to ScopedResourceLibrary on IEventHub \r\n",
    "[10:05:52 Information] [1] Shared.Core.Events.EventHub::Register : Registering event PackFileContainerManipulationEvent to ScopedResourceLibrary on IEventHub \r\n",
    "[10:05:52 Information] [1] Shared.Core.Events.EventHub::Register : Registering event SelectionChangedEvent to TransformToolViewModel on IEventHub \r\n",
    "[10:05:52 Information] [1] Shared.Core.Events.EventHub::Register : Registering event SelectionChangedEvent to GizmoComponent on IEventHub \r\n",
    "[10:05:52 Information] [1] Shared.Core.Events.EventHub::Register : Registering event CommandStackChangedEvent to MenuBarViewModel on IEventHub \r\n",
    "[10:05:52 Information] [1] Shared.Core.Events.EventHub::Register : Registering event SelectionChangedEvent to MenuBarViewModel on IEventHub \r\n",
    "[10:05:52 Information] [1] Shared.Core.Events.EventHub::Register : Registering event KitbasherSkeletonChangedEvent to AnimationControllerViewModel on IEventHub \r\n",
    "[10:05:52 Information] [1] Shared.Core.Events.EventHub::Register : Registering event SceneNodeSelectedEvent to SceneExplorerContextMenuHandler on IEventHub \r\n",
    "[10:05:52 Information] [1] Shared.Core.Events.EventHub::Register : Registering event CommandStackUndoEvent to CommandStackRenderer on IEventHub \r\n",
    "[10:05:52 Information] [1] Shared.Core.Events.EventHub::Register : Registering event CommandStackChangedEvent to CommandStackRenderer on IEventHub \r\n",
    "[10:05:52 Information] [1] Shared.Core.Events.EventHub::Register : Registering event SceneNodeSelectedEvent to SceneNodeEditorViewModel on IEventHub \r\n",
    "[10:05:52 Information] [1] Shared.Core.Events.EventHub::Register : Registering event ScopedFileSavedEvent to KitbasherViewModel on IEventHub \r\n",
    "[10:05:52 Information] [1] Shared.Core.Events.EventHub::Register : Registering event CommandStackChangedEvent to KitbasherViewModel on IEventHub \r\n",
    "[10:05:52 Information] [1] Shared.Core.Events.EventHub::Register : Registering event KitbasherSkeletonChangedEvent to SkeletonChangedHandler on IEventHub \r\n",
    "[10:05:52 Information] [1] AssetEditor.Services.EditorManager::CreateFromFile : Opening grn_orc_gorbad_axe_1h_01.rigid_model_v2 with KitbasherViewModel \r\n",
    "[10:05:52 Information] [1] Shared.GameFormats.RigidModel.ModelFactory::Load : Loading RmvFile. Bytes:109790 \r\n",
    "[10:05:52 Information] [1] Shared.Core.ToolCreation.EditorDatabase::GetViewTypeFromViewModel : Getting view for ViewModel - Editors.KitbasherEditor.ViewModels.KitbasherViewModel \r\n",
    "[10:05:52 Information] [1] Shared.Core.Events.EventHub::Register : Registering event SelectionChangedEvent to MultiSelectTreeView on IEventHub \r\n",
    "[10:05:52 Information] [1] Shared.Core.Events.EventHub::Register : Registering event SceneObjectAddedEvent to MultiSelectTreeView on IEventHub \r\n",
    "[10:05:52 Information] [1] Shared.Core.Events.EventHub::Register : Registering event SceneObjectRemovedEvent to MultiSelectTreeView on IEventHub \r\n",
    "[10:05:56 Information] [1] GameWorld.Core.Services.CommandExecutor::ExecuteCommand : Executing ObjectSelectionCommand \r\n",
    "[10:05:56 Information] [1] GameWorld.Core.Commands.Object.ObjectSelectionCommand::Execute : Command info - Remove[False] Mod[False] Items[grn_orc_gorbad_axe_1h_01_lod01] \r\n",
    "[10:06:02 Information] [1] Shared.Core.Events.EventHub::UnRegister : UnRegistering all events from SceneNodeEditorViewModel from IEventHub \r\n",
    "[10:06:02 Information] [1] Shared.Core.Events.EventHub::UnRegister : UnRegistering all events from RenderEngineComponent from IEventHub \r\n",
    "[10:06:02 Fatal] [1] AssetEditor.App::DispatcherUnhandledExceptionHandler : System.NullReferenceException: Object reference not set to an instance of an object.\r\n   at KitbasherEditor.Views.MultiSelectTreeView.SendNodeSelectionEvent() in C:\\Users\\ole_k\\source\\repos\\TheAssetEditor\\Editors\\KitbasherEditor\\Core\\SceneExplorer\\MultiSelectTreeView.cs:line 136\r\n   at KitbasherEditor.Views.MultiSelectTreeView.SelectionEventHandler(SelectionChangedEvent notification) in C:\\Users\\ole_k\\source\\repos\\TheAssetEditor\\Editors\\KitbasherEditor\\Core\\SceneExplorer\\MultiSelectTreeView.cs:line 115\r\n   at Shared.Core.Events.EventHub.Publish[T](T instance) in C:\\Users\\ole_k\\source\\repos\\TheAssetEditor\\Shared\\SharedCore\\Events\\EventHub.cs:line 90\r\n   at GameWorld.Core.Components.Selection.SelectionManager.SelectionManager_SelectionChanged(ISelectionState state, Boolean sendEvent) in C:\\Users\\ole_k\\source\\repos\\TheAssetEditor\\GameWorld\\View3D\\Components\\Selection\\SelectionManager.cs:line 106\r\n   at GameWorld.Core.Components.Selection.SelectionManager.Dispose() in C:\\Users\\ole_k\\source\\repos\\TheAssetEditor\\GameWorld\\View3D\\Components\\Selection\\SelectionManager.cs:line 164\r\n   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.Dispose()\r\n   at Shared.Core.DependencyInjection.ScopeRepository.RemoveScope(IEditorInterface owner) in C:\\Users\\ole_k\\source\\repos\\TheAssetEditor\\Shared\\SharedCore\\DependencyInjection\\ScopeRepository.cs:line 59\r\n   at Shared.Core.ToolCreation.EditorDatabase.DestroyEditor(IEditorInterface instance) in C:\\Users\\ole_k\\source\\repos\\TheAssetEditor\\Shared\\SharedCore\\ToolCreation\\EditorDatabase.cs:line 165\r\n   at AssetEditor.Services.EditorManager.CloseTool(IEditorInterface tool) in C:\\Users\\ole_k\\source\\repos\\TheAssetEditor\\AssetEditor\\Services\\EditorManager.cs:line 174\r\n   at AssetEditor.ViewModels.MainViewModel.CloseTool(IEditorInterface tool) in C:\\Users\\ole_k\\source\\repos\\TheAssetEditor\\AssetEditor\\ViewModels\\MainViewModel.cs:line 78\r\n   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)\r\n   at System.Windows.Controls.Button.OnClick()\r\n   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)\r\n   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)\r\n   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)\r\n   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)\r\n   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)\r\n   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)\r\n   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)\r\n   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)\r\n   at System.Windows.Input.InputManager.ProcessStagingArea()\r\n   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)\r\n   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean\u0026 handled)\r\n   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean\u0026 handled)\r\n   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)\r\n   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler) \r\n",
    "[10:06:02 Information] [1] Shared.Core.ToolCreation.EditorDatabase::GetViewTypeFromViewModel : Getting view for ViewModel - Editors.KitbasherEditor.ViewModels.KitbasherViewModel \r\n",
    "[10:06:02 Information] [1] Shared.Core.Events.EventHub::Register : Registering event SelectionChangedEvent to MultiSelectTreeView on IEventHub \r\n",
    "[10:06:02 Information] [1] Shared.Core.Events.EventHub::Register : Registering event SceneObjectAddedEvent to MultiSelectTreeView on IEventHub \r\n",
    "[10:06:02 Information] [1] Shared.Core.Events.EventHub::Register : Registering event SceneObjectRemovedEvent to MultiSelectTreeView on IEventHub \r\n"
  ],
  "UserMessage": "",
  "Culture": "en-GB",
  "OSVersion": "Microsoft Windows NT 10.0.19045.0"
}

here's the error message. This happens to me after like 5 to 10 minutes of using the app and it basically happens no matter what I do.

**Comment by donkeyProgramming** [comment]
Fixed in latest version
