### ISSUE TITLE
Music wem files corrupt on export

### ISSUE THREAD

**Issue by Pear-231** [donkeyProgramming/TheAssetEditor#227]
When exporting music wem files they are corrupted. This is confirmed via exporting the same file from RPFM and inspecting the files in HxD which shows they are different. This means the Audio Explorer does not play music files. It's not an issue with the audio tools but with file parsing. An example file is 252393580.wem. My suspicion is because music pack data is encrypted.

**Comment by donkeyProgramming** [comment]
Resolved in other issue
