### ISSUE TITLE
Closing Super View

### ISSUE THREAD

**Issue by DerpyNewb** [donkeyProgramming/TheAssetEditor#231]
{
  "ActivePackFiles": [
    {
      "IsMainEditable": false,
      "IsCa": true,
      "Name": "All Game Packs - Warhammer III",
      "SystemPath": "L:\\SteamLibrary\\steamapps\\common\\Total War WARHAMMER III\\data"
    },
    {
      "IsMainEditable": true,
      "IsCa": false,
      "Name": "!!!derpy_looted_assets",
      "SystemPath": "L:\\SteamLibrary\\steamapps\\common\\Total War WARHAMMER III\\data\\!!!derpy_looted_assets.pack"
    }
  ],
  "CurrentGame": 11,
  "Settings": {
    "RecentPackFilePaths": [
      "L:\\SteamLibrary\\steamapps\\workshop\\content\\1142710\\3256148905\\ZC_MODDING_ASSETS.pack",
      "L:\\SteamLibrary\\steamapps\\workshop\\content\\1142710\\3341513338\\!!!derpy_emp_assets.pack",
      "L:\\SteamLibrary\\steamapps\\workshop\\content\\1142710\\3244046096\\!!!!derpy_resources.pack",
      "L:\\SteamLibrary\\steamapps\\workshop\\content\\1142710\\3297605217\\!!!derpy_chd_assets.pack",
      "L:\\SteamLibrary\\steamapps\\common\\Total War WARHAMMER III\\data\\!!!derpy_looted_assets.pack"
    ],
    "Theme": 0,
    "RenderEngineBackgroundColour": 1,
    "StartMaximised": true,
    "GameDirectories": [
      {
        "Game": 1,
        "Path": null
      },
      {
        "Game": 13,
        "Path": null
      },
      {
        "Game": 5,
        "Path": null
      },
      {
        "Game": 7,
        "Path": null
      },
      {
        "Game": 12,
        "Path": null
      },
      {
        "Game": 9,
        "Path": "L:\\SteamLibrary\\steamapps\\common\\Total War WARHAMMER III\\data"
      },
      {
        "Game": 10,
        "Path": null
      },
      {
        "Game": 11,
        "Path": "L:\\SteamLibrary\\steamapps\\common\\Total War WARHAMMER III\\data"
      }
    ],
    "CurrentGame": 11,
    "LoadCaPacksByDefault": true,
    "LoadWemFiles": true,
    "IsFirstTimeStartingApplication": false,
    "IsDeveloperRun": false,
    "WwisePath": "",
    "OnlyLoadLod0ForReferenceMeshes": true
  },
  "NumberOfOpenEditors": 1,
  "NumberOfOpenedEditors": 2,
  "RunTimeInSeconds": 86.5943842,
  "AssetEditorVersion": "0.57",
  "ExceptionInfo": [
    {
      "Message": "Object reference not set to an instance of an object.",
      "StackTrace": [
        "   at Shared.Core.Events.EventHub.UnRegister(Object owner) in C:\\Users\\ole_k\\source\\repos\\TheAssetEditor\\Shared\\SharedCore\\Events\\EventHub.cs:line 111\r",
        "   at Editors.AnimationMeta.SuperView.SuperViewViewModel.Close() in C:\\Users\\ole_k\\source\\repos\\TheAssetEditor\\Editors\\AnimationMeta\\SuperView\\SuperViewViewModel.cs:line 103\r",
        "   at AssetEditor.Services.EditorManager.CloseTool(IEditorInterface tool) in C:\\Users\\ole_k\\source\\repos\\TheAssetEditor\\AssetEditor\\Services\\EditorManager.cs:line 175\r",
        "   at AssetEditor.ViewModels.MainViewModel.CloseTool(IEditorInterface tool) in C:\\Users\\ole_k\\source\\repos\\TheAssetEditor\\AssetEditor\\ViewModels\\MainViewModel.cs:line 78\r",
        "   at CommunityToolkit.Mvvm.Input.RelayCommand\u00601.Execute(Object parameter)\r",
        "   at System.Windows.Controls.Button.OnClick()\r",
        "   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)\r",
        "   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)\r",
        "   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)\r",
        "   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)\r",
        "   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)\r",
        "   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)\r",
        "   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)\r",
        "   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)\r",
        "   at System.Windows.Input.InputManager.ProcessStagingArea()\r",
        "   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)\r",
        "   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean\u0026 handled)\r",
        "   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean\u0026 handled)\r",
        "   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)\r",
        "   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)\r",
        "   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)"
      ]
    }
  ],
  "CurrentEditorName": "SuperViewViewModel",
  "EditorInputFile": "",
  "EditorInputFileFull": "",
  "EditorInputFilePack": "",
  "LogHistory": [
    "[07:03:34 Information] [1] Shared.GameFormats.RigidModel.ModelFactory::Load : Loading RmvFile. Bytes:21010 \r\n",
    "[07:03:34 Information] [1] GameWorld.Core.Services.ComplexMeshLoader::Load : Attempting to load file dlc02_stump_waist_hu5.rigid_model_v2 \r\n",
    "[07:03:34 Information] [1] Shared.GameFormats.RigidModel.ModelFactory::Load : Loading RmvFile. Bytes:24626 \r\n",
    "[07:03:34 Information] [1] GameWorld.Core.Services.ComplexMeshLoader::Load : Attempting to load file dlc02_stump_head_hu5.rigid_model_v2 \r\n",
    "[07:03:34 Information] [1] Shared.GameFormats.RigidModel.ModelFactory::Load : Loading RmvFile. Bytes:25070 \r\n",
    "[07:03:34 Information] [1] Shared.GameFormats.Animation.AnimationFile::Create : Loading animation: humanoid05.anim Size:6085 \r\n",
    "[07:03:38 Information] [1] Shared.GameFormats.Animation.AnimationFile::Create : Loading animation: hu5_gorduz_axe_shield_docking.anim Size:2321 \r\n",
    "[07:03:38 Information] [1] Shared.GameFormats.Animation.AnimationFile::Create : Loading animation: hu5_gorduz_axe_shield_docking.anim Size:2321 \r\n",
    "[07:03:38 Information] [1] Shared.GameFormats.Animation.AnimationFile::Create : Loading animation: hu5_gorduz_axe_shield_docking.anim Size:2321 \r\n",
    "[07:03:38 Information] [1] Shared.GameFormats.Animation.AnimationFile::Create : Loading animation: hu5_gorduz_axe_shield_docking.anim Size:2321 \r\n",
    "[07:03:43 Information] [1] Shared.GameFormats.Animation.AnimationFile::Create : Loading animation: hu5_gorduz_axe_shield_stand_idle_02.anim Size:31014 \r\n",
    "[07:03:43 Information] [1] Shared.GameFormats.Animation.AnimationFile::Create : Loading animation: hu5_gorduz_axe_shield_docking.anim Size:2321 \r\n",
    "[07:03:43 Information] [1] Shared.GameFormats.Animation.AnimationFile::Create : Loading animation: hu5_gorduz_axe_shield_docking.anim Size:2321 \r\n",
    "[07:03:43 Information] [1] Shared.GameFormats.Animation.AnimationFile::Create : Loading animation: hu5_gorduz_axe_shield_docking.anim Size:2321 \r\n",
    "[07:03:43 Information] [1] Shared.GameFormats.Animation.AnimationFile::Create : Loading animation: hu5_gorduz_axe_shield_docking.anim Size:2321 \r\n",
    "[07:03:43 Information] [1] Shared.GameFormats.Animation.AnimationFile::Create : Loading animation: hu5_gorduz_axe_shield_docking.anim Size:2321 \r\n",
    "[07:03:43 Information] [1] Shared.GameFormats.Animation.AnimationFile::Create : Loading animation: hu5_gorduz_axe_shield_docking.anim Size:2321 \r\n",
    "[07:04:09 Information] [1] Shared.Core.DependencyInjection.ScopeRepository::RemoveScope : Removing scope for Super view of type Editors.AnimationMeta.SuperView.SuperViewViewModel \r\n",
    "[07:04:09 Information] [1] Shared.Core.Events.EventHub::UnRegister : UnRegistering all events from RenderEngineComponent from IEventHub \r\n",
    "[07:04:09 Information] [1] Shared.Core.Events.EventHub::UnRegister : UnRegistering all events from SelectionManager from IEventHub \r\n",
    "[07:04:09 Information] [1] Shared.Core.Events.EventHub::UnRegister : UnRegistering all events from SelectionManager from IEventHub \r\n",
    "[07:04:09 Information] [1] Shared.Core.Events.EventHub::UnRegister : UnRegistering all events from CommandStackRenderer from IEventHub \r\n",
    "[07:04:09 Information] [1] Shared.Core.Events.EventHub::UnRegister : UnRegistering all events from CommandStackRenderer from IEventHub \r\n",
    "[07:04:09 Information] [1] Shared.Core.Events.EventHub::UnRegister : UnRegistering all events from ScopedResourceLibrary from IEventHub \r\n",
    "[07:04:09 Information] [1] Shared.Core.Events.EventHub::UnRegister : UnRegistering all events from RenderEngineComponent from IEventHub \r\n",
    "[07:04:09 Information] [1] Shared.Core.Events.EventHub::UnRegister : UnRegistering all events from CommandStackRenderer from IEventHub \r\n",
    "[07:04:09 Information] [1] Shared.Core.Events.EventHub::UnRegister : UnRegistering all events from SelectionManager from IEventHub \r\n",
    "[07:04:09 Information] [1] Shared.Core.Events.EventHub::UnRegister : UnRegistering all events from RenderEngineComponent from IEventHub \r\n",
    "[07:04:09 Information] [1] Shared.Core.Events.EventHub::UnRegister : UnRegistering all events from SuperViewViewModel from IEventHub \r\n",
    "[07:04:09 Fatal] [1] AssetEditor.App::DispatcherUnhandledExceptionHandler : System.NullReferenceException: Object reference not set to an instance of an object.\r\n   at Shared.Core.Events.EventHub.UnRegister(Object owner) in C:\\Users\\ole_k\\source\\repos\\TheAssetEditor\\Shared\\SharedCore\\Events\\EventHub.cs:line 111\r\n   at Editors.AnimationMeta.SuperView.SuperViewViewModel.Close() in C:\\Users\\ole_k\\source\\repos\\TheAssetEditor\\Editors\\AnimationMeta\\SuperView\\SuperViewViewModel.cs:line 103\r\n   at AssetEditor.Services.EditorManager.CloseTool(IEditorInterface tool) in C:\\Users\\ole_k\\source\\repos\\TheAssetEditor\\AssetEditor\\Services\\EditorManager.cs:line 175\r\n   at AssetEditor.ViewModels.MainViewModel.CloseTool(IEditorInterface tool) in C:\\Users\\ole_k\\source\\repos\\TheAssetEditor\\AssetEditor\\ViewModels\\MainViewModel.cs:line 78\r\n   at CommunityToolkit.Mvvm.Input.RelayCommand\u00601.Execute(Object parameter)\r\n   at System.Windows.Controls.Button.OnClick()\r\n   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)\r\n   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)\r\n   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)\r\n   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)\r\n   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)\r\n   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)\r\n   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)\r\n   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)\r\n   at System.Windows.Input.InputManager.ProcessStagingArea()\r\n   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)\r\n   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean\u0026 handled)\r\n   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean\u0026 handled)\r\n   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)\r\n   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)\r\n   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler) \r\n"
  ],
  "UserMessage": "",
  "Culture": "en-US",
  "OSVersion": "Microsoft Windows NT 10.0.22621.0"
}

**Comment by donkeyProgramming** [comment]
Should be fixed in latest release (0.58). If the bug persist, please reopen
