### ISSUE TITLE
Asset Editor softlocks in Exception (needs to be killed via task manager)

### ISSUE THREAD

**Issue by k2theilian** [donkeyProgramming/TheAssetEditor#232]
When trying to open a .wsmodel the following Error occured: 

{
  "ActivePackFiles": [
    {
      "IsMainEditable": false,
      "IsCa": true,
      "Name": "All Game Packs - Warhammer III",
      "SystemPath": "E:\\SteamLibrary\\steamapps\\common\\Total War WARHAMMER III\\data"
    },
    {
      "IsMainEditable": true,
      "IsCa": false,
      "Name": "Golgguy",
      "SystemPath": "C:\\Users\\username\\Documents\\Golgguy.pack"
    }
  ],
  "CurrentGame": 11,
  "Settings": {
    "RecentPackFilePaths": [
      "C:\\Users\\username\\Documents\\Mods\\Creation\\Drazochan\\ReleasedVer\\Drazchan_.pack",
      "C:\\Users\\username\\Documents\\Golgguy.pack"
    ],
    "Theme": 0,
    "RenderEngineBackgroundColour": 0,
    "StartMaximised": false,
    "GameDirectories": [
      {
        "Game": 9,
        "Path": null
      },
      {
        "Game": 10,
        "Path": null
      },
      {
        "Game": 11,
        "Path": "E:\\SteamLibrary\\steamapps\\common\\Total War WARHAMMER III\\data"
      },
      {
        "Game": 12,
        "Path": null
      },
      {
        "Game": 7,
        "Path": null
      },
      {
        "Game": 4,
        "Path": null
      },
      {
        "Game": 1,
        "Path": null
      }
    ],
    "CurrentGame": 11,
    "LoadCaPacksByDefault": true,
    "LoadWemFiles": true,
    "IsFirstTimeStartingApplication": false,
    "IsDeveloperRun": false,
    "WwisePath": null,
    "OnlyLoadLod0ForReferenceMeshes": true
  },
  "NumberOfOpenEditors": 3,
  "NumberOfOpenedEditors": 9,
  "RunTimeInSeconds": 3597.7855498,
  "AssetEditorVersion": "0.57",
  "ExceptionInfo": [
    {
      "Message": "Begin cannot be called again until End has been successfully called.",
      "StackTrace": [
        "   at GameWorld.Core.Components.Rendering.RenderEngineComponent.Render2DObjects(GraphicsDevice device, CommonShaderParameters commonShaderParameters) in C:\\Users\\ole_k\\source\\repos\\TheAssetEditor\\GameWorld\\View3D\\Components\\Rendering\\RenderEngineComponent.cs:line 166\r",
        "   at GameWorld.Core.Components.Rendering.RenderEngineComponent.Draw(GameTime gameTime) in C:\\Users\\ole_k\\source\\repos\\TheAssetEditor\\GameWorld\\View3D\\Components\\Rendering\\RenderEngineComponent.cs:line 138\r",
        "   at GameWorld.Core.WpfWindow.WpfGame.Render(GameTime time) in C:\\Users\\ole_k\\source\\repos\\TheAssetEditor\\GameWorld\\View3D\\WpfWindow\\WpfGame.cs:line 151"
      ]
    }
  ],
  "CurrentEditorName": "TextEditorViewModel\u00601",
  "EditorInputFile": "kk_ogr_golgfag_01.wsmodel",
  "EditorInputFileFull": "variantmeshes\\wh_variantmodels\\hu13b\\ogr\\ogr_golfgag\\kk_ogr_golgfag_01.wsmodel",
  "EditorInputFilePack": "Golgguy",
  "LogHistory": [
    "[14:23:00 Information] [1] AssetEditor.Services.EditorManager::CreateFromFile : Attempting to open file \u0027kk_ogr_golgfag_01.rigid_model_v2\u0027, but is is already open \r\n",
    "[14:23:00 Information] [1] Shared.Core.ToolCreation.EditorDatabase::GetViewTypeFromViewModel : Getting view for ViewModel - Editors.KitbasherEditor.ViewModels.KitbasherViewModel \r\n",
    "[14:23:00 Information] [1] Shared.Core.Events.EventHub::Register : Registering event SelectionChangedEvent to MultiSelectTreeView on IEventHub \r\n",
    "[14:23:00 Information] [1] Shared.Core.Events.EventHub::Register : Registering event SceneObjectAddedEvent to MultiSelectTreeView on IEventHub \r\n",
    "[14:23:00 Information] [1] Shared.Core.Events.EventHub::Register : Registering event SceneObjectRemovedEvent to MultiSelectTreeView on IEventHub \r\n",
    "[14:23:08 Information] [1] Shared.GameFormats.Animation.AnimationFile::Create : Loading animation: humanoid13b.anim Size:8986 \r\n",
    "[14:23:08 Information] [1] Shared.GameFormats.Animation.AnimationFile::Create : Loading animation: humanoid13b.anim Size:8986 \r\n",
    "[14:23:10 Information] [1] Shared.GameFormats.Animation.AnimationFile::Create : Loading animation: humanoid13b.anim Size:8986 \r\n",
    "[14:23:19 Information] [1] Shared.GameFormats.Animation.AnimationFile::Create : Loading animation: humanoid13b.anim Size:8986 \r\n",
    "[14:25:19 Information] [1] Shared.GameFormats.Animation.AnimationFile::Create : Loading animation: humanoid13b.anim Size:8986 \r\n",
    "[14:25:19 Information] [1] Shared.GameFormats.Animation.AnimationFile::Create : Loading animation: humanoid13b.anim Size:8986 \r\n",
    "[14:25:52 Information] [1] Shared.Core.Events.EventHub::Register : Registering event SelectionChangedEvent to RenderEngineComponent on IEventHub \r\n",
    "[14:25:52 Information] [1] Shared.Core.Events.EventHub::Register : Registering event GraphicDeviceDisposedEvent to ScopedResourceLibrary on IEventHub \r\n",
    "[14:25:52 Information] [1] Shared.Core.Events.EventHub::Register : Registering event PackFileContainerManipulationEvent to ScopedResourceLibrary on IEventHub \r\n",
    "[14:25:52 Information] [1] Shared.Core.Events.EventHub::Register : Registering event SelectionChangedEvent to TransformToolViewModel on IEventHub \r\n",
    "[14:25:52 Information] [1] Shared.Core.Events.EventHub::Register : Registering event SelectionChangedEvent to GizmoComponent on IEventHub \r\n",
    "[14:25:52 Information] [1] Shared.Core.Events.EventHub::Register : Registering event CommandStackChangedEvent to MenuBarViewModel on IEventHub \r\n",
    "[14:25:52 Information] [1] Shared.Core.Events.EventHub::Register : Registering event SelectionChangedEvent to MenuBarViewModel on IEventHub \r\n",
    "[14:25:52 Information] [1] Shared.Core.Events.EventHub::Register : Registering event KitbasherSkeletonChangedEvent to AnimationControllerViewModel on IEventHub \r\n",
    "[14:25:52 Information] [1] Shared.Core.Events.EventHub::Register : Registering event SceneNodeSelectedEvent to SceneExplorerContextMenuHandler on IEventHub \r\n",
    "[14:25:52 Information] [1] Shared.Core.Events.EventHub::Register : Registering event CommandStackUndoEvent to CommandStackRenderer on IEventHub \r\n",
    "[14:25:52 Information] [1] Shared.Core.Events.EventHub::Register : Registering event CommandStackChangedEvent to CommandStackRenderer on IEventHub \r\n",
    "[14:25:52 Information] [1] Shared.Core.Events.EventHub::Register : Registering event SceneNodeSelectedEvent to SceneNodeEditorViewModel on IEventHub \r\n",
    "[14:25:52 Information] [1] Shared.Core.Events.EventHub::Register : Registering event ScopedFileSavedEvent to KitbasherViewModel on IEventHub \r\n",
    "[14:25:52 Information] [1] Shared.Core.Events.EventHub::Register : Registering event CommandStackChangedEvent to KitbasherViewModel on IEventHub \r\n",
    "[14:25:52 Information] [1] Shared.Core.Events.EventHub::Register : Registering event KitbasherSkeletonChangedEvent to SkeletonChangedHandler on IEventHub \r\n",
    "[14:25:52 Information] [1] Shared.Core.DependencyInjection.ScopeRepository::Add : Adding scope for Kitbash Tool of type Editors.KitbasherEditor.ViewModels.KitbasherViewModel \r\n",
    "[14:25:52 Information] [1] AssetEditor.Services.EditorManager::CreateFromFile : Attempting to open file \u0027kk_ogr_golgfag_01.wsmodel\u0027, but is is already open \r\n",
    "[14:25:52 Information] [1] Shared.Core.ToolCreation.EditorDatabase::GetViewTypeFromViewModel : Getting view for ViewModel - Shared.Ui.Editors.TextEditor.TextEditorViewModel\u00601[Shared.Ui.Editors.TextEditor.DefaultTextConverter] \r\n",
    "[14:25:52 Information] [1] Shared.Core.Events.EventHub::UnRegister : UnRegistering all events from MultiSelectTreeView from IEventHub \r\n"
  ],
  "UserMessage": "",
  "Culture": "de-DE",
  "OSVersion": "Microsoft Windows NT 10.0.26100.0"
}

**Comment by donkeyProgramming** [comment]
Should be fixed in latest release (0.58). If the bug persist, please reopen
