### ISSUE TITLE
3K Dismount Animation Problem

### ISSUE THREAD

**Issue by CathayZhao** [donkeyProgramming/TheAssetEditor#61]
Hello and thanks for making this great modding tool! I was working on some animation for Three Kingdoms, infantry or cavalry animation on horse work perfectly fine, but the cavalry animation is bugged when dismounted:
![image](https://user-images.githubusercontent.com/75666345/227658598-eb559d7f-9082-47c8-973b-0117a81c2acc.png)

When checking the vanilla file with rpfm, I notice there is one line in the bin that define the unmount animation:
![image](https://user-images.githubusercontent.com/75666345/227656363-b9b30ef3-4c9d-47bb-a25e-01ac20e0f052.png)

However, that line for cavalry animation bin created using Asset Editor is empty and I thought this might be the reason for the dismount bug:
![image](https://user-images.githubusercontent.com/75666345/227656416-4cd67f32-7e9b-429c-b69f-d4879681ef20.png)
Currently using rpfm edit 3k's animpack will corrupt the whole file, so it is impossible to make cavalry animation that can dismount for 3k now.
It will be great if you can fix this problem. Thanks.

**Comment by donkeyProgramming** [comment]
The mount tool works best with the warhammer games. This bug is unlikely to be addresses so you will have to manually resolve the issue unfortunately

**Comment by CathayZhao** [comment]
Thanks for reply!
