### ISSUE TITLE
Issue with Static models in Rome 2/Attila

### ISSUE THREAD

**Issue by Korgulltheexter** [donkeyProgramming/TheAssetEditor#62]
Recently noticed that when you port models static models like weapons or shields from other games  like Troy or 3K to Rome those models usually get a lot bright even if they aren't textured as metal models. I was suspecting that this was related to texture issue due to the differences between each game, but then I did a test and I turned a weighted model into a static model with Asset editor.  To be more specific I took a mesh from Rome 2 (a helmet with a crest that was attached) then I turned the crest from Weighted into Static, keeping in mind that crests in Rome 2/Attila are static as they need to be attached to the helmets) and noticed that in this process the models get a bug with the lighting as this inverts the light and make the meshes unnecessarily bright.

I attach here some examples. 
![20230207163436_1](https://user-images.githubusercontent.com/73911455/233511774-244fd5d9-02fb-40e7-a4b6-f0738a8ea167.jpg) An example with a Weighted crest turned into Static model (the crest gets a lot of reflection even if it shouldn't reflect the light )
![20230420190434_1](https://user-images.githubusercontent.com/73911455/233512674-dbffe166-a4e9-4f04-903f-c85fab4ff9b7.jpg)
An example of a crest that was turned from Static into Weighted (it works as intended)
![20230321225908_1](https://user-images.githubusercontent.com/73911455/233512031-0f31454d-a6bf-431e-a8ac-355bba28e9f5.jpg) 
![20230321225359_1](https://user-images.githubusercontent.com/73911455/233512182-23003600-5ac1-405b-9a31-834301e35708.jpg) Example of a shield getting the light from the wrong side (also it is suppossed to be a leather shield, so it should look like a metal shield)
![20230110154946_1](https://user-images.githubusercontent.com/73911455/233512287-1385b610-91cf-4743-a91e-e2ec51dcc404.jpg) Example of a club getting the light from the wrong side (it is supposed to be wood and stone and it looks like a metal weapon)

**Comment by donkeyProgramming** [comment]
This issue should be resolved. Please reopen the issue with some provided models if the problem still persists
