### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Brun3125** [donkeyProgramming/TheAssetEditor#89]
Hye Everybody,

I was using asseteditore without any problems, until I've got an error on starting the app now: system.nullReferenceEception (see picture).
Is there something to do to deal with this error.
![nullreferenceexception](https://github.com/donkeyProgramming/TheAssetEditor/assets/88962874/90520724-294e-409f-839b-4db44f996cc6)

**Comment by Brun3125** [comment]
Ok!
I solve my problem by deleting some folders in the users folder.

CHEEERS!

**Comment by donkeyProgramming** [comment]
Fixe for next release
